manager/config/routes.rb
Rails.application.routes.draw do
  root "payment_requests#index"

  resources :payment_requests, only: [:index] do
    patch :accept, on: :member
    patch :reject, on: :member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

manager/app/controllers/payment_requests_controller.rb
require "event_bus"

class PaymentRequestsController < ApplicationController
  include EventBus

  def index
    @payment_requests = PaymentRequest.all.sort_by do |pr|
      PaymentRequest::STATUSES.index(pr.status)
    end
  end

  def accept
    if payment_request.update(status: PaymentRequest::ACCEPTED_STATUS)
      emit_payment_status_updated_event
      redirect_to action: :index
    end
  end

  def reject
    if payment_request.update(status: PaymentRequest::REJECTED_STATUS)
      emit_payment_status_updated_event
      redirect_to action: :index
    end
  end

  private

  def payment_request
    @payment_request ||= PaymentRequest.find(params[:id])
  end

  def emit_payment_status_updated_event
    emit_event(
      "EventBus::PAYMENT_REQUEST_#{payment_request.status.upcase}_EVENT".constantize,
      payment_request,
      PAYMENTS_TOPIC
    )
  end
end

manager/app/helpers/application_helper.rb
module ApplicationHelper
end

manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

manager/app/views/payment_requests/index.html.erb
<h1>List of received Payment Requests</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Description</th>
      <th>Status</th>
      <th>Actions</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_requests.each do |pr| %>
      <tr>
        <td><%= "#{pr.amount} #{pr.currency}" %></td>
        <td><%= pr.description %></td>
        <td><%= pr.status %></td>
        <td>
          <% if pr.status.eql?(PaymentRequest::PENDING_STATUS) %>
            <%= link_to "Accept", accept_payment_request_path(id: pr.id), method: :patch %>
            <%= link_to "Reject", reject_payment_request_path(id: pr.id), method: :patch %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>