contractor/config/routes.rb
Rails.application.routes.draw do
  root "payment_requests#index"

  resources :payment_requests, only: [:index, :new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

contractor/app/models/payment_request.rb
class PaymentRequest < ApplicationRecord
  PENDING_STATUS = "pending"
  ACCEPTED_STATUS = "accepted"
  REJECTED_STATUS = "rejected"
  STATUSES = [PENDING_STATUS, ACCEPTED_STATUS, REJECTED_STATUS].freeze
  AVAILABLE_CURRENCIES = %w[PLN EUR USD GBP CZK].freeze

  validates :amount, :currency, :description, :status, presence: true
  validates :status, inclusion: { in: STATUSES }
  validates :currency, inclusion: { in: AVAILABLE_CURRENCIES }
end

contractor/app/controllers/payment_requests_controller.rb
require "event_bus"

class PaymentRequestsController < ApplicationController
  include EventBus

  def index
    @payment_requests = PaymentRequest.all.sort_by do |pr|
      PaymentRequest::STATUSES.index(pr.status)
    end
  end

  def new
    @payment_request = PaymentRequest.new
  end

  def create
    payment_request = PaymentRequest.create(create_params)
    if payment_request.persisted?
      emit_payment_created_event(payment_request)
      redirect_to action: :index
    else
      redirect_to action: :new
    end
  end

  private

  def create_params
    params.require(:payment_request).permit(
      :amount, :currency, :description, :status
    ).merge(status: PaymentRequest::PENDING_STATUS)
  end

  def emit_payment_created_event(payment_request)
    emit_event(
      PENDING_PAYMENT_REQUEST_CREATED_EVENT, payment_request, PAYMENTS_TOPIC
    )
  end
end

contractor/app/helpers/payment_requests_helper.rb
module PaymentRequestsHelper
end

contractor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contractor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

contractor/app/views/payment_requests/create.html.erb
<h1>PaymentRequests#create</h1>
<p>Find me in app/views/payment_requests/create.html.erb</p>

contractor/app/views/payment_requests/index.html.erb
<h1>Your Payment Requests list</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Description</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_requests.each do |pr| %>
      <tr>
        <td><%= "#{pr.amount} #{pr.currency}" %></td>
        <td><%= pr.description %></td>
        <td><%= pr.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Payment Request", new_payment_request_path %>

contractor/app/views/payment_requests/new.html.erb
<h1>Create new Payment Requests</h1>

<%= form_with model: @payment_request, url: payment_requests_path, method: :post do |f| %>
  <%= f.label :amount %>
  <%= f.number_field :amount, required: true %>
  <br><br>
  <%= f.label :currency %>
  <%= f.select :currency, PaymentRequest::AVAILABLE_CURRENCIES %>
  <br><br>
  <%= f.label :description %>
  <%= f.text_field :description, required: true %>
  <br><br>
  <%= f.submit %>
<% end %>

<br><br>

<%= link_to "Return to Payment Request list", root_path %>